import type { AgentAssignmentContract, AgentAssignmentScopeType, AgentDefinitionContract, AgentRuntimeProfile, CurrentUserContract, DepartmentContract, DepartmentRole, EmployeeDirectoryEntryContract, PermissionAction, PermissionEffect, PermissionResource, PermissionScopeType } from '@enterprise-brain/contracts';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AdminApiClient, AdminApiError } from './api-client.js';

type Page = 'Dashboard' | 'Departments' | 'Employees' | 'Agents';
const permissionPairs: Array<[PermissionResource, PermissionAction]> = [['ORGANIZATION','VIEW'],['DEPARTMENT','VIEW'],['DEPARTMENT','MANAGE'],['DEPARTMENT','ASSIGN'],['PERMISSION','VIEW'],['PERMISSION','MANAGE'],['RESULT','REVIEW'],['AGENT','VIEW'],['AGENT','MANAGE'],['AGENT','ASSIGN'],['AGENT','EXECUTE']];
const errorMessage = (cause: unknown) => cause instanceof Error ? cause.message : 'Request failed.';

function useLoad<T>(load: () => Promise<T>, deps: React.DependencyList) {
  const [value,setValue]=useState<T>(); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const epoch=useRef(0);
  const reload=useCallback(()=>{const id=++epoch.current;setLoading(true);setError('');void load().then(v=>{if(id===epoch.current)setValue(v);}).catch(e=>{if(id===epoch.current)setError(errorMessage(e));}).finally(()=>{if(id===epoch.current)setLoading(false);});},deps);
  useEffect(reload,[reload]); return {value,error,loading,reload};
}
function State({data,empty=false}:{data:{loading:boolean;error:string;reload:()=>void};empty?:boolean}){if(data.loading)return <p className="muted">Loading…</p>;if(data.error)return <div className="local-error"><p>{data.error}</p><button className="secondary" onClick={data.reload}>Retry</button></div>;if(empty)return <p className="muted">Nothing to show yet.</p>;return null;}
function Badge({value}:{value:string}){return <span className={`badge ${value==='DENY'||value==='DISABLED'?'danger-badge':value==='ALLOW'||value==='ACTIVE'?'success-badge':''}`}>{value}</span>}
function PageFrame({title,children}:{title:string;children:React.ReactNode}){return <div className="page"><div><p className="eyebrow">Administration</p><h2>{title}</h2></div>{children}</div>}

export function App(){
  const tokenRef=useRef(sessionStorage.getItem('admin-token')??''); const generation=useRef(0); const [token,setToken]=useState(tokenRef.current); const [user,setUser]=useState<CurrentUserContract>(); const [denied,setDenied]=useState(false); const [page,setPage]=useState<Page>('Dashboard');
  const signOut=useCallback(()=>{generation.current++;tokenRef.current='';sessionStorage.removeItem('admin-token');setToken('');setUser(undefined);setDenied(false);setPage('Dashboard');},[]);
  const api=useMemo(()=>new AdminApiClient(()=>tokenRef.current,signOut),[signOut]);
  useEffect(()=>{if(!token)return;const id=++generation.current;void api.me().then(identity=>{if(id!==generation.current)return;if(identity.organization?.role==='OWNER'||identity.organization?.role==='ADMIN'){setUser(identity);setDenied(false);}else{setUser(undefined);setDenied(true);}}).catch(e=>{if(id===generation.current&&!(e instanceof AdminApiError&&e.code==='AUTHENTICATION_REQUIRED'))signOut();});},[api,signOut,token]);
  if(!token)return <Login api={api} onSuccess={next=>{tokenRef.current=next;sessionStorage.setItem('admin-token',next);setToken(next);}}/>;
  if(denied)return <main className="login"><section className="card"><h1>Access denied</h1><p>This console is limited to Organization Owners and Admins.</p><button onClick={()=>void api.logout().catch(()=>undefined).finally(signOut)}>Sign out</button></section></main>;
  if(!user)return <main className="center">Loading administrator session…</main>;
  return <main className="shell"><aside><div><p className="eyebrow">Enterprise Brain</p><h1>Control Plane</h1></div><nav>{(['Dashboard','Departments','Employees','Agents']as Page[]).map(item=><button className={item===page?'nav active':'nav'} onClick={()=>setPage(item)} key={item}>{item}</button>)}</nav><small>{user.organization?.name}</small></aside><section className="workspace"><header><span><strong>{user.organization?.name}</strong><small>{user.name} · {user.organization?.role}</small></span><button className="secondary" onClick={()=>void api.logout().catch(()=>undefined).finally(signOut)}>Sign out</button></header>{page==='Dashboard'&&<Dashboard api={api} go={setPage}/>} {page==='Departments'&&<Departments api={api}/>} {page==='Employees'&&<Employees api={api} organizationId={user.organization!.id}/>} {page==='Agents'&&<Agents api={api} organizationId={user.organization!.id}/>}</section></main>;
}
function Login({api,onSuccess}:{api:AdminApiClient;onSuccess:(token:string)=>void}){const[login,setLogin]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{onSuccess((await api.login(login,password)).token);}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}return <main className="login"><form className="card" onSubmit={submit}><p className="eyebrow">Enterprise Brain</p><h1>Admin Console</h1><label>Email<input autoComplete="username" required value={login} onChange={e=>setLogin(e.target.value)}/></label><label>Password<input autoComplete="current-password" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></main>}
function Dashboard({api,go}:{api:AdminApiClient;go:(p:Page)=>void}){const data=useLoad(()=>Promise.all([api.employees(),api.departments(),api.agents()]),[api]);const[employees,departments,agents]=data.value??[[],[],[]];return <PageFrame title="Dashboard"><State data={data}/>{data.value&&<><div className="cards"><Metric label="Employees" value={employees.length}/><Metric label="Departments" value={departments.length}/><Metric label="Active agents" value={agents.filter(a=>a.status==='ACTIVE').length}/></div><div className="actions"><button onClick={()=>go('Departments')}>Add Department</button><button className="secondary" onClick={()=>go('Employees')}>View Employees</button><button className="secondary" onClick={()=>go('Agents')}>Create Agent</button></div></>}</PageFrame>}
function Metric({label,value}:{label:string;value:number}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}

function Departments({api}:{api:AdminApiClient}){const data=useLoad(()=>api.departments(),[api]);const[selected,setSelected]=useState<DepartmentContract>();const members=useLoad(()=>selected?api.departmentMembers(selected.id):Promise.resolve([]),[api,selected?.id]);const[name,setName]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function create(e:React.FormEvent){e.preventDefault();if(busy||!name.trim())return;setBusy(true);setError('');try{await api.createDepartment(name);setName('');data.reload();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}return <PageFrame title="Departments"><div className="two-column"><section className="panel"><form onSubmit={create}><h3>Create department</h3><label>Name<input required value={name} onInput={e=>setName(e.currentTarget.value)} onChange={e=>setName(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'Creating…':'Create Department'}</button></form><State data={data} empty={!data.value?.length}/>{data.value&&<table><thead><tr><th>Name</th><th>Status</th></tr></thead><tbody>{data.value.map(d=><tr className={d.id===selected?.id?'selected':''} onClick={()=>setSelected(d)} key={d.id}><td>{d.name}</td><td><Badge value={d.status}/></td></tr>)}</tbody></table>}</section><section className="panel"><h3>{selected?`${selected.name} members`:'Department members'}</h3>{selected&&<State data={members} empty={!members.value?.length}/>} {members.value?.map(m=><div className="row" key={m.userId}><span>{m.name}</span><Badge value={m.role}/></div>)}</section></div></PageFrame>}

function Employees({api,organizationId}:{api:AdminApiClient;organizationId:string}){const people=useLoad(()=>api.employees(),[api]);const departments=useLoad(()=>api.departments(),[api]);const[selected,setSelected]=useState<EmployeeDirectoryEntryContract>();const[search,setSearch]=useState('');const visible=(people.value??[]).filter(p=>`${p.displayName} ${p.email}`.toLowerCase().includes(search.toLowerCase()));return <PageFrame title="Employees"><label className="search">Search employees<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or email"/></label><div className="two-column employees"><section className="panel"><State data={people} empty={!people.value?.length}/>{people.value&&<table><thead><tr><th>Employee</th><th>Department</th><th>Role</th></tr></thead><tbody>{visible.map(p=><tr key={p.userId} className={p.userId===selected?.userId?'selected':''} onClick={()=>setSelected(p)}><td><strong>{p.displayName}</strong><small>{p.email}</small></td><td>{p.departmentName??'Unassigned'}</td><td>{p.organizationRole}</td></tr>)}</tbody></table>}</section><section className="panel">{selected?<EmployeeDetail api={api} person={selected} departments={departments.value??[]} organizationId={organizationId} refreshed={people.reload}/>:<p className="muted">Select an employee.</p>}</section></div></PageFrame>}
function EmployeeDetail({api,person,departments,organizationId,refreshed}:{api:AdminApiClient;person:EmployeeDirectoryEntryContract;departments:DepartmentContract[];organizationId:string;refreshed:()=>void}){const[departmentId,setDepartmentId]=useState(person.departmentId??'');const[role,setRole]=useState<DepartmentRole>(person.departmentRole??'MEMBER');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const overrides=useLoad(()=>api.overrides(person.userId),[api,person.userId]);async function assign(e:React.FormEvent){e.preventDefault();if(!departmentId||busy)return;setBusy(true);setError('');try{await api.assignDepartment(person.userId,departmentId,role);refreshed();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}return <><h3>{person.displayName}</h3><dl><dt>Email</dt><dd>{person.email}</dd><dt>Account</dt><dd><Badge value={person.accountStatus}/></dd><dt>Organization role</dt><dd>{person.organizationRole}</dd><dt>Department</dt><dd>{person.departmentName??'Unassigned'} {person.departmentRole&&`· ${person.departmentRole}`}</dd></dl><form className="form-row" onSubmit={assign}><label>Department<select value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">Choose department</option>{departments.filter(d=>d.status==='ACTIVE').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as DepartmentRole)}><option>MEMBER</option><option>MANAGER</option></select></label><button disabled={busy||!departmentId}>{busy?'Saving…':'Save assignment'}</button></form>{error&&<p className="error">{error}</p>}<Overrides api={api} userId={person.userId} organizationId={organizationId} departments={departments} data={overrides}/></>}
function Overrides({api,userId,organizationId,departments,data}:{api:AdminApiClient;userId:string;organizationId:string;departments:DepartmentContract[];data:{value?:Array<{id:string;effect:string;resource:string;action:string;scopeType:string}>;loading:boolean;error:string;reload:()=>void}}){const[pair,setPair]=useState('DEPARTMENT:VIEW');const[scopeType,setScopeType]=useState<PermissionScopeType>('ORGANIZATION');const[scopeId,setScopeId]=useState(organizationId);const[effect,setEffect]=useState<PermissionEffect>('ALLOW');const[busy,setBusy]=useState(false);const[confirmId,setConfirmId]=useState('');const[error,setError]=useState('');useEffect(()=>setScopeId(scopeType==='ORGANIZATION'?organizationId:departments[0]?.id??''),[scopeType,organizationId,departments]);async function save(e:React.FormEvent){e.preventDefault();if(busy||!scopeId)return;const[resource,action]=pair.split(':')as[PermissionResource,PermissionAction];setBusy(true);setError('');try{await api.putOverride(userId,{scopeType,scopeId,resource,action,effect});data.reload();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}async function remove(id:string){if(confirmId!==id){setConfirmId(id);return;}setBusy(true);setError('');try{await api.deleteOverride(userId,id);setConfirmId('');data.reload();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}return <section className="subpanel"><h4>Permission overrides</h4><form className="compact-form" onSubmit={save}><label>Permission<select value={pair} onChange={e=>setPair(e.target.value)}>{permissionPairs.map(([r,a])=><option key={`${r}:${a}`}>{r}:{a}</option>)}</select></label><label>Scope<select value={scopeType} onChange={e=>setScopeType(e.target.value as PermissionScopeType)}><option>ORGANIZATION</option><option>DEPARTMENT</option></select></label>{scopeType==='DEPARTMENT'&&<label>Department<select value={scopeId} onChange={e=>setScopeId(e.target.value)}>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}<label>Effect<select value={effect} onChange={e=>setEffect(e.target.value as PermissionEffect)}><option>ALLOW</option><option>DENY</option></select></label><button disabled={busy}>Add override</button></form>{error&&<p className="error">{error}</p>}<State data={data} empty={!data.value?.length}/>{data.value?.map(o=><div className="row" key={o.id}><span><Badge value={o.effect}/> {o.resource}:{o.action} · {o.scopeType}</span>{confirmId===o.id?<span><button className="danger" disabled={busy} onClick={()=>void remove(o.id)}>Confirm delete</button><button className="secondary" onClick={()=>setConfirmId('')}>Cancel</button></span>:<button className="secondary" disabled={busy} onClick={()=>void remove(o.id)}>Delete</button>}</div>)}</section>}

function Agents({api,organizationId}:{api:AdminApiClient;organizationId:string}){const catalog=useLoad(()=>api.agents(),[api]);const departments=useLoad(()=>api.departments(),[api]);const employees=useLoad(()=>api.employees(),[api]);const[selected,setSelected]=useState<AgentDefinitionContract>();const[key,setKey]=useState('');const[name,setName]=useState('');const[description,setDescription]=useState('');const[profile,setProfile]=useState<AgentRuntimeProfile>('READ_ONLY_WORK');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function create(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await api.createAgent({key,name,...(description?{description}:{}),runtimeProfile:profile});setKey('');setName('');setDescription('');catalog.reload();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}return <PageFrame title="Agents"><div className="two-column"><section className="panel"><form onSubmit={create}><h3>Create Agent</h3><label>Key<input required value={key} onChange={e=>setKey(e.target.value)}/></label><label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Description<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Runtime profile<select value={profile} onChange={e=>setProfile(e.target.value as AgentRuntimeProfile)}><option>READ_ONLY_WORK</option><option>CONFIRMED_WRITE_WORK</option></select></label><button disabled={busy}>{busy?'Creating…':'Create Agent'}</button>{error&&<p className="error">{error}</p>}</form><State data={catalog} empty={!catalog.value?.length}/>{catalog.value?.map(a=><div className={a.id===selected?.id?'row selected':'row'} onClick={()=>setSelected(a)} key={a.id}><span><strong>{a.name}</strong><small>{a.key} · v{a.version} · {a.runtimeProfile}</small></span><Badge value={a.status}/></div>)}</section><section className="panel">{selected?<Assignments api={api} agent={selected} organizationId={organizationId} departments={departments.value??[]} employees={employees.value??[]}/>:<p className="muted">Select an Agent.</p>}</section></div></PageFrame>}
function Assignments({api,agent,organizationId,departments,employees}:{api:AdminApiClient;agent:AgentDefinitionContract;organizationId:string;departments:DepartmentContract[];employees:EmployeeDirectoryEntryContract[]}){const data=useLoad(()=>api.assignments(agent.id),[api,agent.id]);const[scopeType,setScopeType]=useState<AgentAssignmentScopeType>('ORGANIZATION');const[scopeId,setScopeId]=useState(organizationId);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[confirmId,setConfirmId]=useState('');const options=scopeType==='ORGANIZATION'?[{id:organizationId,name:'Entire organization'}]:scopeType==='DEPARTMENT'?departments.map(d=>({id:d.id,name:d.name})):employees.map(e=>({id:e.userId,name:`${e.displayName} (${e.email})`}));useEffect(()=>setScopeId(options[0]?.id??''),[scopeType,organizationId,departments,employees]);async function add(e:React.FormEvent){e.preventDefault();if(busy||!scopeId)return;setBusy(true);setError('');try{await api.assignAgent(agent.id,scopeType,scopeId);data.reload();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}async function remove(a:AgentAssignmentContract){if(confirmId!==a.id){setConfirmId(a.id);return;}setBusy(true);setError('');try{await api.deleteAssignment(agent.id,a.id);setConfirmId('');data.reload();}catch(cause){setError(errorMessage(cause));}finally{setBusy(false);}}return <><h3>{agent.name} assignments</h3><form className="compact-form" onSubmit={add}><label>Scope type<select value={scopeType} onChange={e=>setScopeType(e.target.value as AgentAssignmentScopeType)}><option>ORGANIZATION</option><option>DEPARTMENT</option><option>USER</option></select></label><label>Scope<select value={scopeId} onChange={e=>setScopeId(e.target.value)}>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><button disabled={busy||!scopeId}>Assign</button></form>{error&&<p className="error">{error}</p>}<State data={data} empty={!data.value?.length}/>{data.value?.map(a=><div className="row" key={a.id}><span>{a.scopeType} · <small>{a.scopeId}</small> · <Badge value={a.status}/></span>{confirmId===a.id?<span><button className="danger" disabled={busy} onClick={()=>void remove(a)}>Confirm delete</button><button className="secondary" onClick={()=>setConfirmId('')}>Cancel</button></span>:<button className="secondary" disabled={busy} onClick={()=>void remove(a)}>Delete</button>}</div>)}</>}
