import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { createApp } from '../../apps/api/src/app.js';
import { createPrismaClient, encodePassword, hashSessionToken } from '../../packages/database/src/index.js';
const url = process.env.DATABASE_URL; const database = url ? createPrismaClient(url) : undefined;
const db = () => { if (!database) throw new Error('DATABASE_URL is required'); return database; };
const now = new Date('2026-09-03T00:00:00.000Z');
async function token(userId: string) { const raw = `token-${userId}-${'x'.repeat(40)}`; await db().account.create({ data: { id: `account-${userId}`, userId, login: `${userId}@test.local`, passwordHash: await encodePassword('Password!2026'), status: 'ACTIVE', createdAt: now, updatedAt: now } }); await db().session.create({ data: { id: `session-${userId}`, accountId: `account-${userId}`, tokenHash: hashSessionToken(raw), createdAt: now, expiresAt: new Date(now.getTime() + 86400000) } }); return { authorization: `Bearer ${raw}` }; }
async function fixture() {
  await db().organization.create({ data: { id: 'org-a', name: 'Enterprise Brain Demo', status: 'ACTIVE', createdAt: now, updatedAt: now } });
  await db().organization.create({ data: { id: 'org-b', name: 'Other', status: 'ACTIVE', createdAt: now, updatedAt: now } });
  for (const user of ['owner', 'admin', 'member', 'manager', 'employee', 'outsider']) await db().user.create({ data: { id: user, name: user, systemRole: 'EMPLOYEE', createdAt: now, updatedAt: now } });
  for (const [id, userId, organizationId, role] of [['om-owner','owner','org-a','OWNER'],['om-admin','admin','org-a','ADMIN'],['om-member','member','org-a','MEMBER'],['om-manager','manager','org-a','MEMBER'],['om-employee','employee','org-a','MEMBER'],['om-outsider','outsider','org-b','MEMBER']] as const) await db().organizationMembership.create({ data: { id, userId, organizationId, role, status: 'ACTIVE', createdAt: now, updatedAt: now } });
  await db().department.createMany({ data: [{ id: 'product', organizationId: 'org-a', name: 'Product', status: 'ACTIVE', createdAt: now, updatedAt: now }, { id: 'research', organizationId: 'org-a', name: 'Research', status: 'ACTIVE', createdAt: now, updatedAt: now }, { id: 'other-dept', organizationId: 'org-b', name: 'Other', status: 'ACTIVE', createdAt: now, updatedAt: now }] });
  await db().departmentMembership.createMany({ data: [{ id: 'dm-manager', organizationId: 'org-a', departmentId: 'product', userId: 'manager', role: 'MANAGER', status: 'ACTIVE', createdAt: now, updatedAt: now }, { id: 'dm-employee', organizationId: 'org-a', departmentId: 'product', userId: 'employee', role: 'MEMBER', status: 'ACTIVE', createdAt: now, updatedAt: now }] });
}
async function clean() { await db().session.deleteMany(); await db().account.deleteMany(); await db().humanConfirmation.deleteMany(); await db().review.deleteMany(); await db().resultArtifact.deleteMany(); await db().result.deleteMany(); await db().artifact.deleteMany(); await db().agentToolCall.deleteMany(); await db().agentRun.deleteMany(); await db().taskDependency.deleteMany(); await db().taskAssignment.deleteMany(); await db().task.deleteMany(); await db().projectMember.deleteMany(); await db().project.deleteMany(); await db().departmentMembership.deleteMany(); await db().organizationMembership.deleteMany(); await db().department.deleteMany(); await db().organization.deleteMany(); await db().user.deleteMany(); }
describe('Organization API', () => {
  beforeEach(clean); afterAll(async () => database?.$disconnect());
  it('returns Session-derived organization and department context from /me', async () => { await fixture(); const app = await createApp({ prisma: db() }); const headers = await token('manager'); const response = await app.inject({ method: 'GET', url: '/me', headers }); expect(response.statusCode).toBe(200); expect(response.json()).toMatchObject({ id: 'manager', organization: { id: 'org-a', name: 'Enterprise Brain Demo', role: 'MEMBER' }, department: { id: 'product', name: 'Product', role: 'MANAGER' } }); await app.close(); });
  it('allows owner/admin management while rejecting member and cross-organization forgery', async () => { await fixture(); const app = await createApp({ prisma: db() }); const owner = await token('owner'); const admin = await token('admin'); const member = await token('member'); const created = await app.inject({ method: 'POST', url: '/departments', headers: owner, payload: { name: 'Design' } }); expect(created.statusCode).toBe(201); const updated = await app.inject({ method: 'PATCH', url: `/departments/${created.json().id}`, headers: admin, payload: { status: 'DISABLED' } }); expect(updated.statusCode).toBe(200);
    expect((await app.inject({ method: 'POST', url: '/departments', headers: member, payload: { name: 'Nope' } })).statusCode).toBe(403);
    expect((await app.inject({ method: 'PUT', url: '/employees/employee/department', headers: owner, payload: { departmentId: 'research', role: 'MEMBER', actorId: 'admin', organizationId: 'org-b' } })).statusCode).toBe(400);
    expect((await app.inject({ method: 'PUT', url: '/employees/outsider/department', headers: owner, payload: { departmentId: 'research', role: 'MEMBER' } })).statusCode).toBe(404);
    expect((await app.inject({ method: 'PUT', url: '/employees/employee/department', headers: owner, payload: { departmentId: 'other-dept', role: 'MEMBER' } })).statusCode).toBe(404); expect((await db().departmentMembership.findUniqueOrThrow({ where: { userId: 'employee' } })).departmentId).toBe('product'); await app.close(); });
  it('moves an employee between departments through the owner Session without creating a second membership', async () => { await fixture(); const app = await createApp({ prisma: db() }); const owner = await token('owner'); const response = await app.inject({ method: 'PUT', url: '/employees/employee/department', headers: owner, payload: { departmentId: 'research', role: 'MANAGER' } }); expect(response.statusCode).toBe(200); expect(response.json()).toMatchObject({ userId: 'employee', role: 'MANAGER' }); expect(await db().departmentMembership.count({ where: { userId: 'employee' } })).toBe(1); expect((await db().departmentMembership.findUniqueOrThrow({ where: { userId: 'employee' } })).departmentId).toBe('research'); await app.close(); });
  it('permits a department manager to list only their own department members', async () => { await fixture(); const app = await createApp({ prisma: db() }); const headers = await token('manager'); expect((await app.inject({ method: 'GET', url: '/departments/product/members', headers })).statusCode).toBe(200); expect((await app.inject({ method: 'GET', url: '/departments/research/members', headers })).statusCode).toBe(403); await app.close(); });
});
