/* eslint-disable @typescript-eslint/no-explicit-any -- Fastify request bodies are schema-validated at this route boundary. */
import type { FastifyInstance } from 'fastify';
import { AgentService } from './agent-service.js';
const id={type:'object',additionalProperties:false,required:['agentId'],properties:{agentId:{type:'string',minLength:1}}} as const;
const assignmentId={type:'object',additionalProperties:false,required:['agentId','assignmentId'],properties:{agentId:{type:'string',minLength:1},assignmentId:{type:'string',minLength:1}}} as const;
const create={type:'object',additionalProperties:false,required:['key','name','runtimeProfile'],properties:{key:{type:'string',minLength:1},name:{type:'string',minLength:1},description:{type:'string'},runtimeProfile:{enum:['READ_ONLY_WORK','CONFIRMED_WRITE_WORK']}}} as const;
const patch={type:'object',additionalProperties:false,minProperties:1,properties:{name:{type:'string',minLength:1},description:{type:'string'},status:{enum:['ACTIVE','DISABLED']}}} as const;
const assignment={type:'object',additionalProperties:false,required:['scopeType','scopeId'],properties:{scopeType:{enum:['ORGANIZATION','DEPARTMENT','USER']},scopeId:{type:'string',minLength:1}}} as const;
export function registerAgentRoutes(app:FastifyInstance,service:AgentService){app.get('/agents',async r=>service.list(r.requestContext));app.post<{Body:any}>('/agents',{schema:{body:create}},async r=>({ ...(await service.create(r.requestContext,r.body as any)) }));app.patch<{Params:{agentId:string};Body:any}>('/agents/:agentId',{schema:{params:id,body:patch}},async r=>service.update(r.requestContext,r.params.agentId,r.body as any));app.get<{Params:{agentId:string}}>('/agents/:agentId/assignments',{schema:{params:id}},async r=>service.assignments(r.requestContext,r.params.agentId));app.put<{Params:{agentId:string};Body:any}>('/agents/:agentId/assignments',{schema:{params:id,body:assignment}},async r=>service.assign(r.requestContext,r.params.agentId,r.body as any));app.delete<{Params:{agentId:string;assignmentId:string}}>('/agents/:agentId/assignments/:assignmentId',{schema:{params:assignmentId}},async(r,reply)=>{await service.remove(r.requestContext,r.params.agentId,r.params.assignmentId);return reply.code(204).send();});app.get('/me/agents',async r=>({agents:await service.available(r.requestContext)}));}
