/* eslint-disable @typescript-eslint/no-explicit-any -- Prisma relation payloads are intentionally narrowed at contract edge. */
import { randomUUID } from 'node:crypto';
import type { AgentAssignmentContract, AgentAssignmentScopeType, AgentDefinitionContract, AgentRuntimeProfile, AvailableAgentContract } from '@enterprise-brain/contracts';
import type { PrismaClient } from '../generated/prisma/client.js';
import { evaluatePermission, type PermissionDbClient } from './permission-repository.js';

export class AgentCatalogRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async listForAdmin(userId: string): Promise<AgentDefinitionContract[] | 'NOT_FOUND' | 'FORBIDDEN'> { return this.prisma.$transaction(async tx => {
    const actor = await activeActor(tx, userId); if (!actor) return 'NOT_FOUND';
    const allowed = await evaluatePermission(tx, { organizationId: actor.organizationId, userId, scopeType: 'ORGANIZATION', scopeId: actor.organizationId, resource: 'AGENT', action: 'MANAGE' });
    if (!allowed.allowed) return 'FORBIDDEN';
    return (await tx.agentDefinition.findMany({ where: { organizationId: actor.organizationId }, include: { versions: { where: { status: 'ACTIVE' }, orderBy: { version: 'desc' }, take: 1 } }, orderBy: { key: 'asc' } })).flatMap(row => row.versions[0] ? [definitionContract(row, row.versions[0])] : []);
  }, { isolationLevel: 'RepeatableRead' }); }
  async create(userId: string, input: { key:string; name:string; description?:string; runtimeProfile:AgentRuntimeProfile }): Promise<AgentDefinitionContract | 'NOT_FOUND' | 'FORBIDDEN'> { return this.prisma.$transaction(async tx => {
    const actor=await activeActor(tx,userId); if(!actor)return 'NOT_FOUND'; const p=await evaluatePermission(tx,{organizationId:actor.organizationId,userId,scopeType:'ORGANIZATION',scopeId:actor.organizationId,resource:'AGENT',action:'MANAGE'}); if(!p.allowed)return 'FORBIDDEN'; const now=new Date(); const row=await tx.agentDefinition.create({data:{id:randomUUID(),organizationId:actor.organizationId,key:input.key,name:input.name,description:input.description,status:'ACTIVE',createdAt:now,updatedAt:now}}); const version=await tx.agentVersion.create({data:{id:randomUUID(),agentDefinitionId:row.id,version:1,runtimeProfile:input.runtimeProfile,status:'ACTIVE',createdAt:now}}); return definitionContract(row,version);
  }, { isolationLevel: 'RepeatableRead' }); }
  async update(userId:string,id:string,input:{name?:string;description?:string;status?:'ACTIVE'|'DISABLED'}):Promise<AgentDefinitionContract|'NOT_FOUND'|'FORBIDDEN'>{return this.prisma.$transaction(async tx=>{const actor=await activeActor(tx,userId);if(!actor)return 'NOT_FOUND';const row=await tx.agentDefinition.findFirst({where:{id,organizationId:actor.organizationId},include:{versions:{where:{status:'ACTIVE'},orderBy:{version:'desc'},take:1}}});if(!row)return 'NOT_FOUND';const p=await evaluatePermission(tx,{organizationId:actor.organizationId,userId,scopeType:'ORGANIZATION',scopeId:actor.organizationId,resource:'AGENT',action:'MANAGE'});if(!p.allowed)return 'FORBIDDEN';const updated=await tx.agentDefinition.update({where:{id},data:{...input,updatedAt:new Date()}});return row.versions[0]?definitionContract(updated,row.versions[0]):'NOT_FOUND';},{isolationLevel:'RepeatableRead'});}
  async assignments(userId:string,id:string):Promise<AgentAssignmentContract[]|'NOT_FOUND'|'FORBIDDEN'>{return this.prisma.$transaction(async tx=>{const actor=await activeActor(tx,userId);if(!actor)return 'NOT_FOUND';const d=await tx.agentDefinition.findFirst({where:{id,organizationId:actor.organizationId}});if(!d)return 'NOT_FOUND';const p=await evaluatePermission(tx,{organizationId:actor.organizationId,userId,scopeType:'ORGANIZATION',scopeId:actor.organizationId,resource:'AGENT',action:'ASSIGN'});if(!p.allowed)return 'FORBIDDEN';return (await tx.agentAssignment.findMany({where:{agentDefinitionId:id,organizationId:actor.organizationId},orderBy:{createdAt:'asc'}})).map(assignmentContract);},{isolationLevel:'RepeatableRead'});}
  async assign(userId:string,id:string,input:{scopeType:AgentAssignmentScopeType;scopeId:string}):Promise<AgentAssignmentContract|'NOT_FOUND'|'FORBIDDEN'>{return this.prisma.$transaction(async tx=>{const actor=await activeActor(tx,userId);if(!actor)return 'NOT_FOUND';const d=await tx.agentDefinition.findFirst({where:{id,organizationId:actor.organizationId}});if(!d)return 'NOT_FOUND';const p=await evaluatePermission(tx,{organizationId:actor.organizationId,userId,scopeType:'ORGANIZATION',scopeId:actor.organizationId,resource:'AGENT',action:'ASSIGN'});if(!p.allowed)return 'FORBIDDEN';if(!(await scopeExists(tx,actor.organizationId,input)))return 'NOT_FOUND';const now=new Date();const row=await tx.agentAssignment.upsert({where:{organizationId_agentDefinitionId_scopeType_scopeId:{organizationId:actor.organizationId,agentDefinitionId:id,...input}},create:{id:randomUUID(),organizationId:actor.organizationId,agentDefinitionId:id,...input,status:'ACTIVE',createdAt:now,updatedAt:now},update:{status:'ACTIVE',updatedAt:now}});return assignmentContract(row);},{isolationLevel:'RepeatableRead'});}
  async removeAssignment(userId:string,id:string,assignmentId:string):Promise<boolean|'NOT_FOUND'|'FORBIDDEN'>{return this.prisma.$transaction(async tx=>{const actor=await activeActor(tx,userId);if(!actor)return 'NOT_FOUND';const d=await tx.agentDefinition.findFirst({where:{id,organizationId:actor.organizationId}});if(!d)return 'NOT_FOUND';const p=await evaluatePermission(tx,{organizationId:actor.organizationId,userId,scopeType:'ORGANIZATION',scopeId:actor.organizationId,resource:'AGENT',action:'ASSIGN'});if(!p.allowed)return 'FORBIDDEN';return (await tx.agentAssignment.deleteMany({where:{id:assignmentId,agentDefinitionId:id,organizationId:actor.organizationId}})).count===1||'NOT_FOUND';},{isolationLevel:'RepeatableRead'});}
  async availableForUser(userId:string):Promise<AvailableAgentContract[]>{return this.prisma.$transaction(async tx=>{const member=await tx.organizationMembership.findFirst({where:{userId,status:'ACTIVE',organization:{status:'ACTIVE'}},include:{departmentMembership:true}});if(!member)return [];const assignments=await tx.agentAssignment.findMany({where:{organizationId:member.organizationId,status:'ACTIVE',OR:[{scopeType:'ORGANIZATION',scopeId:member.organizationId},{scopeType:'USER',scopeId:userId},...(member.departmentMembership?.status==='ACTIVE'?[{scopeType:'DEPARTMENT' as const,scopeId:member.departmentMembership.departmentId}]:[])]},include:{definition:{include:{versions:{where:{status:'ACTIVE'},orderBy:{version:'desc'},take:1}}}}});const byId=new Map<string,AvailableAgentContract>();for(const a of assignments){const v=a.definition.versions[0];if(a.definition.status!=='ACTIVE'||!v)continue;const existing=byId.get(a.agentDefinitionId);const source=a.scopeType;if(existing){if(!existing.assignmentSources.includes(source))existing.assignmentSources.push(source);continue;}byId.set(a.agentDefinitionId,{id:a.definition.id,key:a.definition.key,name:a.definition.name,...(a.definition.description?{description:a.definition.description}:{}),version:v.version,runtimeProfile:v.runtimeProfile,assignmentSources:[source]});}return [...byId.values()].sort((a,b)=>a.key.localeCompare(b.key));},{isolationLevel:'RepeatableRead'});}
}
async function activeActor(tx:PermissionDbClient,userId:string){return tx.organizationMembership.findFirst({where:{userId,status:'ACTIVE',organization:{status:'ACTIVE'}}});}
async function scopeExists(tx:PermissionDbClient,organizationId:string,input:{scopeType:AgentAssignmentScopeType;scopeId:string}){if(input.scopeType==='ORGANIZATION')return input.scopeId===organizationId;if(input.scopeType==='DEPARTMENT')return !!(await tx.department.findFirst({where:{id:input.scopeId,organizationId,status:'ACTIVE'}}));return !!(await tx.organizationMembership.findFirst({where:{userId:input.scopeId,organizationId,status:'ACTIVE'}}));}
function definitionContract(row:any,v:any):AgentDefinitionContract{return{id:row.id,organizationId:row.organizationId,key:row.key,name:row.name,...(row.description?{description:row.description}:{}),status:row.status,version:v.version,runtimeProfile:v.runtimeProfile,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
function assignmentContract(row:any):AgentAssignmentContract{return{id:row.id,organizationId:row.organizationId,agentDefinitionId:row.agentDefinitionId,scopeType:row.scopeType,scopeId:row.scopeId,status:row.status,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
