import { randomUUID } from 'node:crypto';
import type { AccountStatusChangeContract, AuditEventContract, AuditEventListContract } from '@enterprise-brain/contracts';
import type { PrismaClient, Prisma } from '../generated/prisma/client.js';
type AuditDb=Pick<PrismaClient,'auditEvent'>; type MembershipDb=Pick<PrismaClient,'organizationMembership'>;

export type AuditAccess = 'NOT_FOUND'|'FORBIDDEN'|'CANNOT_MODIFY_SELF'|'LAST_ACTIVE_OWNER'|'INVALID_REASON';
export class AuditRepository {
  constructor(private readonly prisma:PrismaClient) {}
  async append(input:{organizationId:string;actorUserId:string;action:string;subjectType:string;subjectId?:string;resourceType:string;resourceId?:string;before?:Record<string,unknown>;after?:Record<string,unknown>;reason?:string;source:'ADMIN_API'|'SYSTEM';requestId?:string}, db:AuditDb=this.prisma){return db.auditEvent.create({data:{id:randomUUID(),...input,before:input.before as Prisma.InputJsonValue|undefined,after:input.after as Prisma.InputJsonValue|undefined,createdAt:new Date()}});}
  async listForOrganization(actorUserId:string,input:{cursor?:string;limit?:number;action?:string;actorUserId?:string;subjectId?:string}):Promise<AuditEventListContract|AuditAccess>{return this.prisma.$transaction(async tx=>{const actor=await activeAdmin(tx,actorUserId);if(typeof actor==='string')return actor;const limit=Math.min(Math.max(input.limit??50,1),100);const cursor=parseCursor(input.cursor);const where={organizationId:actor.organizationId,...(input.action?{action:input.action}:{}),...(input.actorUserId?{actorUserId:input.actorUserId}:{}),...(input.subjectId?{subjectId:input.subjectId}:{}),...(cursor?{OR:[{createdAt:{lt:cursor.createdAt}},{createdAt:cursor.createdAt,id:{lt:cursor.id}}]}:{})};const rows=await tx.auditEvent.findMany({where,include:{actor:{include:{account:true}}},orderBy:[{createdAt:'desc'},{id:'desc'}],take:limit+1});const page=rows.slice(0,limit);return {items:page.map(row=>toContract(row)),...(rows.length>limit?{nextCursor:encodeCursor(page.at(-1)!)}:{})};},{isolationLevel:'RepeatableRead'});}
  async changeAccountStatus(actorUserId:string,targetUserId:string,status:'ACTIVE'|'DISABLED',reason:string):Promise<AccountStatusChangeContract|AuditAccess>{return this.prisma.$transaction(async tx=>{const actor=await activeAdmin(tx,actorUserId);if(typeof actor==='string')return actor;const trimmed=reason.trim();if(trimmed.length<3||trimmed.length>500)return 'INVALID_REASON';const target=await tx.organizationMembership.findFirst({where:{organizationId:actor.organizationId,userId:targetUserId,status:'ACTIVE'},include:{user:{include:{account:true}}}});if(!target||!target.user.account)return 'NOT_FOUND';const account=target.user.account;if(targetUserId===actorUserId)return 'CANNOT_MODIFY_SELF';if(actor.role==='ADMIN'&&target.role!=='MEMBER')return 'FORBIDDEN';if(status==='DISABLED'&&target.role==='OWNER'){const owners=await tx.organizationMembership.count({where:{organizationId:actor.organizationId,role:'OWNER',status:'ACTIVE'}});if(owners<=1)return 'LAST_ACTIVE_OWNER';}if(account.status===status)return {userId:targetUserId,status};const before={status:account.status};await tx.account.update({where:{id:account.id},data:{status,updatedAt:new Date()}});if(status==='DISABLED')await tx.session.updateMany({where:{accountId:account.id,revokedAt:null},data:{revokedAt:new Date()}});await this.append({organizationId:actor.organizationId,actorUserId,action:'ACCOUNT_STATUS_CHANGED',subjectType:'USER',subjectId:targetUserId,resourceType:'ACCOUNT',resourceId:account.id,before,after:{status},reason:trimmed,source:'ADMIN_API'},tx);return {userId:targetUserId,status};},{isolationLevel:'RepeatableRead'});}
}
async function activeAdmin(db:MembershipDb,userId:string):Promise<{organizationId:string;role:'OWNER'|'ADMIN'|'MEMBER'}|AuditAccess>{const member=await db.organizationMembership.findFirst({where:{userId,status:'ACTIVE',organization:{status:'ACTIVE'},user:{account:{status:'ACTIVE'}}}});if(!member)return 'NOT_FOUND';return member.role==='OWNER'||member.role==='ADMIN'?{organizationId:member.organizationId,role:member.role}:'FORBIDDEN';}
function toContract(row:{id:string;organizationId:string;actorUserId:string;action:string;subjectType:string;subjectId:string|null;resourceType:string;resourceId:string|null;before:unknown;after:unknown;reason:string|null;source:'ADMIN_API'|'SYSTEM';requestId:string|null;createdAt:Date;actor:{name:string;account:{login:string}|null}}):AuditEventContract{return {id:row.id,organizationId:row.organizationId,actorUserId:row.actorUserId,actorDisplayName:row.actor.name,...(row.actor.account?{actorEmail:row.actor.account.login}:{}),action:row.action,subjectType:row.subjectType,...(row.subjectId?{subjectId:row.subjectId}:{}),resourceType:row.resourceType,...(row.resourceId?{resourceId:row.resourceId}:{}),...(row.before?{before:row.before as Record<string,unknown>}:{}),...(row.after?{after:row.after as Record<string,unknown>}:{}),...(row.reason?{reason:row.reason}:{}),source:row.source,...(row.requestId?{requestId:row.requestId}:{}),createdAt:row.createdAt.toISOString()};}
function encodeCursor(row:{createdAt:Date;id:string}){return Buffer.from(`${row.createdAt.toISOString()}|${row.id}`).toString('base64url');}function parseCursor(value?:string){if(!value)return;try{const [date,id]=Buffer.from(value,'base64url').toString().split('|');const createdAt=new Date(date);return Number.isNaN(+createdAt)||!id?undefined:{createdAt,id};}catch{return undefined;}}
