/* eslint-disable @typescript-eslint/no-explicit-any -- Prisma's generated row unions are intentionally normalized here. */
import { randomUUID } from 'node:crypto';
import type {
  ActionItemContract, ConversationContract, ConversationListQuery, ConversationScopeType, CreateConversationRequest,
  CreateMessageRequest, CursorPage, LibraryItemContract, LibraryListQuery, MessageContract, NotificationContract, NotificationListQuery,
  ReminderContract, ReminderStatus, SwarmEventContract, SwarmEventListQuery
} from '@enterprise-brain/contracts';
import type { PrismaClient } from '../generated/prisma/client.js';

type Access = 'NOT_FOUND' | 'FORBIDDEN' | 'INVALID';
type Tx = Omit<PrismaClient, '$connect' | '$disconnect' | '$on' | '$use' | '$extends'>;
const page = (limit?: number) => Math.max(1, Math.min(limit ?? 20, 50));
const cursor = (value?: string) => value ? JSON.parse(Buffer.from(value, 'base64url').toString()) as { at: string; id: string } : undefined;
const next = (at: Date, id: string) => Buffer.from(JSON.stringify({ at: at.toISOString(), id })).toString('base64url');

export class CollaborationRepository {
  constructor(private readonly prisma: PrismaClient) {}

  async createConversation(userId: string, input: CreateConversationRequest): Promise<ConversationContract | Access> {
    return this.prisma.$transaction(async tx => {
      const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND';
      const participants = [...new Set([userId, ...input.participantUserIds])];
      if (input.type === 'HUMAN_DM' && participants.length !== 2) return 'INVALID';
      if (input.type !== 'HUMAN_DM' && input.type !== 'AI_THREAD' && !participants.length) return 'INVALID';
      if (!(await scopeVisible(tx, userId, member.organizationId, input.scopeType, input.scopeId))) return 'NOT_FOUND';
      if (input.type === 'AI_THREAD' && (input.scopeType !== 'USER' || input.scopeId !== userId)) return 'INVALID';
      const valid = await tx.organizationMembership.count({ where: { organizationId: member.organizationId, userId: { in: participants }, status: 'ACTIVE', organization: { status: 'ACTIVE' }, user: { account: { status: 'ACTIVE' } } } });
      if (valid !== participants.length) return 'NOT_FOUND';
      const now = new Date(); const row = await tx.conversation.create({ data: { id: randomUUID(), organizationId: member.organizationId, type: input.type, scopeType: input.scopeType, scopeId: input.scopeId, title: input.title, createdByUserId: userId, createdAt: now, updatedAt: now, participants: { createMany: { data: participants.map(participantUserId => ({ userId: participantUserId, createdAt: now })) } } } });
      return conversation(row);
    }, { isolationLevel: 'RepeatableRead' });
  }

  async listConversations(userId: string, input: ConversationListQuery): Promise<CursorPage<ConversationContract> | Access> {
    return this.prisma.$transaction(async tx => {
      const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const limit = page(input.limit); const parsed = cursor(input.cursor);
      const rows = await tx.conversation.findMany({ where: { organizationId: member.organizationId, ...(input.type ? { type: input.type } : {}), ...(input.scopeType ? { scopeType: input.scopeType } : {}), ...(input.scopeId ? { scopeId: input.scopeId } : {}) }, orderBy: [{ updatedAt: 'desc' }, { id: 'desc' }] });
      const visible: ConversationContract[] = []; for (const row of rows) if (await visibleConversation(tx, userId, row)) visible.push(conversation(row));
      const after = parsed ? visible.filter(row => row.updatedAt < parsed.at || (row.updatedAt === parsed.at && row.conversationId < parsed.id)) : visible;
      const items = after.slice(0, limit); const last = items.at(-1); return { items, nextCursor: after.length > limit && last ? next(new Date(last.updatedAt), last.conversationId) : null };
    }, { isolationLevel: 'RepeatableRead' });
  }

  async getConversation(userId: string, id: string): Promise<ConversationContract | Access> { return this.prisma.$transaction(async tx => { const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const row = await tx.conversation.findFirst({ where: { id, organizationId: member.organizationId } }); return row && await visibleConversation(tx, userId, row) ? conversation(row) : 'NOT_FOUND'; }, { isolationLevel: 'RepeatableRead' }); }

  async createMessage(userId: string, conversationId: string, input: CreateMessageRequest, idempotencyKey: string): Promise<MessageContract | Access> {
    return this.prisma.$transaction(async tx => {
      const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const conversationRow = await tx.conversation.findFirst({ where: { id: conversationId, organizationId: member.organizationId } });
      if (!conversationRow || !(await visibleConversation(tx, userId, conversationRow))) return 'NOT_FOUND'; if (!input.content.trim() || !idempotencyKey.trim()) return 'INVALID';
      const existing = await tx.message.findFirst({ where: { conversationId, authorUserId: userId, idempotencyKey } }); if (existing) return message(existing);
      if (input.replyToMessageId && !(await tx.message.findFirst({ where: { id: input.replyToMessageId, conversationId } }))) return 'NOT_FOUND';
      const mentioned = [...new Set(input.mentionedUserIds ?? [])]; const valid = !mentioned.length || await tx.organizationMembership.count({ where: { organizationId: member.organizationId, userId: { in: mentioned }, status: 'ACTIVE' } }) === mentioned.length; if (!valid) return 'NOT_FOUND';
      const now = new Date(); const row = await tx.message.create({ data: { id: randomUUID(), conversationId, authorType: 'USER', authorUserId: userId, content: input.content, replyToMessageId: input.replyToMessageId, mentionedUserIds: mentioned, mentionedAgentIds: input.mentionedAgentIds ?? [], idempotencyKey, createdAt: now } }); await tx.conversation.update({ where: { id: conversationId }, data: { updatedAt: now } }); return message(row);
    }, { isolationLevel: 'RepeatableRead' });
  }

  async listMessages(userId: string, conversationId: string, input: { cursor?: string; limit?: number }): Promise<CursorPage<MessageContract> | Access> { return this.prisma.$transaction(async tx => { const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const c = await tx.conversation.findFirst({ where: { id: conversationId, organizationId: member.organizationId } }); if (!c || !(await visibleConversation(tx, userId, c))) return 'NOT_FOUND'; const limit = page(input.limit); const parsed = cursor(input.cursor); const rows = await tx.message.findMany({ where: { conversationId }, orderBy: [{ createdAt: 'asc' }, { id: 'asc' }] }); const after = parsed ? rows.filter(row => row.createdAt.toISOString() > parsed.at || (row.createdAt.toISOString() === parsed.at && row.id > parsed.id)) : rows; const items = after.slice(0, limit).map(message); const last = items.at(-1); return { items, nextCursor: after.length > limit && last ? next(new Date(last.createdAt), last.messageId) : null }; }, { isolationLevel: 'RepeatableRead' }); }

  async notifications(userId: string, input: NotificationListQuery): Promise<CursorPage<NotificationContract> | Access> { return this.prisma.$transaction(async tx => { const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const limit = page(input.limit); const parsed = cursor(input.cursor); const rows = await tx.notification.findMany({ where: { organizationId: member.organizationId, recipientUserId: userId, ...(input.unreadOnly ? { readAt: null } : {}) }, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }] }); const after = parsed ? rows.filter(row => row.createdAt.toISOString() < parsed.at || (row.createdAt.toISOString() === parsed.at && row.id < parsed.id)) : rows; const items = after.slice(0, limit).map(notification); const last = items.at(-1); return { items, nextCursor: after.length > limit && last ? next(new Date(last.createdAt), last.notificationId) : null }; }, { isolationLevel: 'RepeatableRead' }); }
  async markNotification(userId: string, id: string, read: boolean): Promise<NotificationContract | Access> { return this.prisma.$transaction(async tx => { const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const row = await tx.notification.findFirst({ where: { id, organizationId: member.organizationId, recipientUserId: userId } }); if (!row) return 'NOT_FOUND'; return notification(await tx.notification.update({ where: { id }, data: { readAt: read ? new Date() : null } })); }, { isolationLevel: 'RepeatableRead' }); }

  async createReminder(userId: string, input: { type: string; title: string; dueAt: string; deepLink: string }): Promise<ReminderContract | Access> { return this.prisma.$transaction(async tx => { const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const dueAt = new Date(input.dueAt); if (!input.title.trim() || Number.isNaN(+dueAt)) return 'INVALID'; const now = new Date(); return reminder(await tx.reminder.create({ data: { id: randomUUID(), organizationId: member.organizationId, userId, type: input.type as never, title: input.title, dueAt, status: 'SCHEDULED', deepLink: input.deepLink, createdAt: now, updatedAt: now } })); }, { isolationLevel: 'RepeatableRead' }); }
  async listReminders(userId: string, input: { cursor?: string; limit?: number }): Promise<CursorPage<ReminderContract> | Access> { return this.prisma.$transaction(async tx => { const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const limit = page(input.limit); const rows = await tx.reminder.findMany({ where: { organizationId: member.organizationId, userId }, orderBy: [{ dueAt: 'asc' }, { id: 'asc' }], take: limit + 1 }); const items = rows.slice(0, limit).map(reminder); return { items, nextCursor: rows.length > limit && items.at(-1) ? next(new Date(items.at(-1)!.dueAt), items.at(-1)!.reminderId) : null }; }, { isolationLevel: 'RepeatableRead' }); }
  async updateReminder(userId: string, id: string, input: { title?: string; dueAt?: string; status?: ReminderStatus; deepLink?: string }): Promise<ReminderContract | Access> { return this.prisma.$transaction(async tx => { const member = await activeMember(tx, userId); if (!member) return 'NOT_FOUND'; const row = await tx.reminder.findFirst({ where: { id, organizationId: member.organizationId, userId } }); if (!row) return 'NOT_FOUND'; const dueAt = input.dueAt ? new Date(input.dueAt) : undefined; if (dueAt && Number.isNaN(+dueAt)) return 'INVALID'; return reminder(await tx.reminder.update({ where: { id }, data: { ...input, dueAt, updatedAt: new Date() } })); }, { isolationLevel: 'RepeatableRead' }); }

  async library(userId: string, input: LibraryListQuery): Promise<CursorPage<LibraryItemContract> | Access> { return this.prisma.$transaction(async tx => { const member=await activeMember(tx,userId);if(!member) return 'NOT_FOUND'; const artifacts = await tx.artifact.findMany({ where: { task: { project: { members: { some: { userId } } } } }, orderBy: { createdAt: 'desc' } }); const results = await tx.result.findMany({ where: { task: { project: { members: { some: { userId } } } } }, orderBy: { createdAt: 'desc' } }); const rows: LibraryItemContract[] = [...artifacts.map(row => ({ libraryItemId: `artifact:${row.id}`, organizationId: member.organizationId, type: 'ARTIFACT' as const, scopeType: 'PROJECT' as const, scopeId: row.projectId, title: row.relativePath, summary: null, sourceObjectId: row.id, sourceObjectType: 'ARTIFACT', createdByUserId: row.createdByUserId, createdAt: row.createdAt.toISOString(), updatedAt: row.createdAt.toISOString() })), ...results.map(row => ({ libraryItemId: `result:${row.id}`, organizationId: member.organizationId, type: 'RESULT' as const, scopeType: 'PROJECT' as const, scopeId: row.projectId, title: `Result ${row.id}`, summary: null, sourceObjectId: row.id, sourceObjectType: 'RESULT', createdByUserId: row.createdByUserId, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() }))].filter(row => (!input.type || row.type === input.type) && (!input.scopeType || row.scopeType === input.scopeType) && (!input.scopeId || row.scopeId === input.scopeId)).sort((a,b) => b.createdAt.localeCompare(a.createdAt) || b.libraryItemId.localeCompare(a.libraryItemId)); const limit = page(input.limit); return { items: rows.slice(0, limit), nextCursor: rows.length > limit && rows[limit - 1] ? next(new Date(rows[limit - 1].createdAt), rows[limit - 1].libraryItemId) : null }; }, { isolationLevel: 'RepeatableRead' }); }
  async libraryItem(userId:string,id:string):Promise<LibraryItemContract|Access>{const rows=await this.library(userId,{});if(typeof rows==='string')return rows;return rows.items.find(row=>row.libraryItemId===id)||'NOT_FOUND';}
  async swarmEvents(userId:string,input:SwarmEventListQuery):Promise<CursorPage<SwarmEventContract>|Access>{return this.prisma.$transaction(async tx=>{const member=await activeMember(tx,userId);if(!member)return'NOT_FOUND';const visible=input.scopeType==='DEPARTMENT'?member.departmentMembership?.status==='ACTIVE'&&member.departmentMembership.departmentId===input.scopeId:!!await tx.projectMember.findFirst({where:{projectId:input.scopeId,userId}});if(!visible)return'NOT_FOUND';const limit=page(input.limit);const rows=await tx.swarmEvent.findMany({where:{organizationId:member.organizationId,scopeType:input.scopeType,scopeId:input.scopeId,...(input.type?{type:input.type}:{})},orderBy:[{occurredAt:'desc'},{id:'desc'}],take:limit+1});const items=rows.slice(0,limit).map(swarm);return{items,nextCursor:rows.length>limit&&items.at(-1)?next(new Date(items.at(-1)!.occurredAt),items.at(-1)!.swarmEventId):null};},{isolationLevel:'RepeatableRead'});}
  async actionItems(userId:string):Promise<ActionItemContract[]|Access>{return this.prisma.$transaction(async tx=>{const member=await activeMember(tx,userId);if(!member)return'NOT_FOUND';const [confirmations,results,mentions]=await Promise.all([tx.humanConfirmation.findMany({where:{userId,status:'PENDING'}}),tx.result.findMany({where:{createdByUserId:userId,status:'CANDIDATE'}}),tx.message.findMany({where:{mentionedUserIds:{has:userId}},include:{conversation:true}})]);return[...confirmations.map(row=>({actionItemId:`confirmation:${row.id}`,organizationId:member.organizationId,assigneeUserId:userId,type:'CONFIRM_ARTIFACT' as const,title:'Confirm artifact',deepLink:`/confirmations/${row.id}`,status:'OPEN' as const,dueAt:null,createdAt:row.createdAt.toISOString(),completedAt:null})),...results.map(row=>({actionItemId:`result:${row.id}`,organizationId:member.organizationId,assigneeUserId:userId,type:'SUBMIT_RESULT' as const,title:'Submit result',deepLink:`/results/${row.id}`,status:'OPEN' as const,dueAt:null,createdAt:row.createdAt.toISOString(),completedAt:null})),...mentions.filter(row=>row.conversation.organizationId===member.organizationId).map(row=>({actionItemId:`mention:${row.id}`,organizationId:member.organizationId,assigneeUserId:userId,type:'REPLY_MENTION' as const,title:'Reply to mention',deepLink:`/conversations/${row.conversationId}`,status:'OPEN' as const,dueAt:null,createdAt:row.createdAt.toISOString(),completedAt:null}))];},{isolationLevel:'RepeatableRead'});}
}

async function activeMember(tx:Tx,userId:string){return tx.organizationMembership.findFirst({where:{userId,status:'ACTIVE',organization:{status:'ACTIVE'},user:{account:{status:'ACTIVE'}}},include:{departmentMembership:true}});}
async function scopeVisible(tx:Tx,userId:string,organizationId:string,type:ConversationScopeType,id:string){if(type==='USER')return id===userId;if(type==='DEPARTMENT')return !!await tx.department.findFirst({where:{id,organizationId,status:'ACTIVE'}});if(type==='PROJECT')return !!await tx.projectMember.findFirst({where:{projectId:id,userId}});const task=await tx.task.findUnique({where:{id}});return !!task&&!!await tx.projectMember.findFirst({where:{projectId:task.projectId,userId}});}
async function visibleConversation(tx:Tx,userId:string,row:{type:string;scopeType:string;scopeId:string;createdByUserId:string;id:string}){if(row.type==='AI_THREAD')return row.createdByUserId===userId;if(row.type==='HUMAN_GROUP'||row.type==='HUMAN_DM')return !!await tx.conversationParticipant.findUnique({where:{conversationId_userId:{conversationId:row.id,userId}}});if(row.scopeType==='PROJECT')return !!await tx.projectMember.findFirst({where:{projectId:row.scopeId,userId}});if(row.scopeType==='TASK'){const task=await tx.task.findUnique({where:{id:row.scopeId}});return !!task&&!!await tx.projectMember.findFirst({where:{projectId:task.projectId,userId}});}return row.createdByUserId===userId;}
function conversation(row:any):ConversationContract{return{conversationId:row.id,organizationId:row.organizationId,type:row.type,scopeType:row.scopeType,scopeId:row.scopeId,title:row.title,createdByUserId:row.createdByUserId,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
function message(row:any):MessageContract{return{messageId:row.id,conversationId:row.conversationId,authorType:row.authorType,authorUserId:row.authorUserId,authorAgentId:row.authorAgentId,content:row.content,replyToMessageId:row.replyToMessageId,mentionedUserIds:row.mentionedUserIds,mentionedAgentIds:row.mentionedAgentIds,createdAt:row.createdAt.toISOString(),editedAt:row.editedAt?.toISOString()??null};}
function notification(row:any):NotificationContract{return{notificationId:row.id,organizationId:row.organizationId,recipientUserId:row.recipientUserId,type:row.type as NotificationContract['type'],title:row.title,body:row.body,deepLink:row.deepLink,readAt:row.readAt?.toISOString()??null,createdAt:row.createdAt.toISOString()};}
function reminder(row:any):ReminderContract{return{reminderId:row.id,organizationId:row.organizationId,userId:row.userId,type:row.type,title:row.title,dueAt:row.dueAt.toISOString(),status:row.status,deepLink:row.deepLink,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
function swarm(row:any):SwarmEventContract{return{swarmEventId:row.id,organizationId:row.organizationId,scopeType:row.scopeType,scopeId:row.scopeId,type:row.type,actorUserId:row.actorUserId,title:row.title,summary:row.summary,deepLink:row.deepLink,occurredAt:row.occurredAt.toISOString()};}
